### ISSUE TITLE
佬适配下ARM64版

### ISSUE THREAD

**Issue by feiniao025** [trustyboy/xxqg-helper#1]

**Comment by trustyboy** [comment]
暂时缺ARM64环境，你可以用源码自己构建下镜像先试试。

**Comment by feiniao025** [comment]
> 暂时缺ARM64环境，你可以用源码自己构建下镜像先试试。

buildx 插件实现多架构镜像是否可行?

**Comment by feiniao025** [comment]
> 暂时缺ARM64环境，你可以用源码自己构建下镜像先试试。

buildx 插件实现多架构镜像是否可行?

**Comment by trustyboy** [comment]
> > 暂时缺ARM64环境，你可以用源码自己构建下镜像先试试。
> 
> buildx 插件实现多架构镜像是否可行?

已支持，可以试试 #3
