### ISSUE TITLE
win闪退有教程吗大佬

### ISSUE THREAD

**Issue by gebobo123** [trustyboy/xxqg-helper#12]

**Comment by trustyboy** [comment]
win下安装步骤：
1、安装好python 3.9
2、到项目目录执行pip install -r requirements.txt
3、去https://chromedriver.storage.googleapis.com/index.html 下载你机器chrome对应的webdriver 放到App目录
4、然后执行python XueQG.py看看

**Comment by trustyboy** [comment]
#15  0.6版本已支持Win，请到Release中下载
