### ISSUE TITLE
多选题无法识别答案

### ISSUE THREAD

**Issue by jamesbondjava** [trustyboy/xxqg-helper#13]
![ISSUE](https://user-images.githubusercontent.com/57007273/208340295-d82d4648-ada8-442e-afe4-d60fb4a7981d.png)
频繁出现无法识别答案的情况，后面都有将近100个了，吓得我赶紧把docker停了。

**Comment by trustyboy** [comment]
我试试

**Comment by trustyboy** [comment]
是每周答题有问题？

**Comment by jamesbondjava** [comment]
好像是的，只有这里面有问题。

**Comment by trustyboy** [comment]
测试下每周答题没试出来，无法识别目前一般是视频类型的题目
