### ISSUE TITLE
请问如何多用户使用？

### ISSUE THREAD

**Issue by Murphyling01** [trustyboy/xxqg-helper#14]
我这边按照您的命令搭建好了docker版的钉钉推送，钉钉只收到一个二维码登录，登录成功一个账号后，就没有新的登录推送链接了，我该如何设置多个账户登录呢？希望大佬解惑~

**Comment by trustyboy** [comment]
> 我这边按照您的命令搭建好了docker版的钉钉推送，钉钉只收到一个二维码登录，登录成功一个账号后，就没有新的登录推送链接了，我该如何设置多个账户登录呢？希望大佬解惑~

多用户这块目前我还没研究好，我是这么做的，建立了多个docker镜像，分别推送给不同的用户。
