### ISSUE TITLE
不知道什么原因

### ISSUE THREAD

**Issue by gebobo123** [trustyboy/xxqg-helper#18]
DeuTools listeningonws://127.0.0.1:49862/deutools/browser/e713a0b5-8601-4c48-9
0
73-61bf64d54041

1222/064747.212:ERROR:dxua_video_decode_accelerator_win.cc(1460)] DHUAUDA fatal

error: could not LoadLibrary: mf.dll: 找不到指定的模块。(@x?E)

1222/064747.214:ERROR:dxua_video_decode_accelerator_win.cc(1460)] DRUAUDA fatal
error: could not LoadLibrary: mfplat.dll:找不到指定的模块。(0x7E)

1222/064747.216:ERROR:dxua_uideo_decode_accelerator_win.cc(1460>] DHUAUDA fatal
error: could not LoadLibrary: msmpeg2udec.dll:找不到指定的模块。
(0x7E)

1222/064747.218:ERROR:dxua_video_decode_accelerator_win.cc(1468)] DXUAUDA fatal
error: could not LoadLibrary: msuproc.dll:找不到指定的模块。
(0x7E)

正在打开二维码登陆界面,请稍后...

Tracehack (most recent call last):

File "huegG.py", line 37, in <module>

File "funciWuecore.py", line 130, in logging

File"selenium\webdriver remote webdriver.py", line 333, in get

File"selenium\webdriver\remotewebdriver.py", line 321, in execute

File "seleniumwebdriver\remote\errorhandler.py". line 242, in check_response

selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR

PROKY CONNECTION_FAILED
(Session info: headless chrome=101.0.4951.6?)
[8900] Failed to execute script XueQG

**Comment by trustyboy** [comment]
重试多次会出现吗

**Comment by gebobo123** [comment]
是

**Comment by trustyboy** [comment]
前面那几个找不到模块的错误可能是你系统缺失了Media Pack导致，但可能不是报错主要原因。应该是最后`net::ERR PROKY CONNECTION_FAILED` ，尝试检查下你电脑是否设置了代理，环境变量检查下有没有http_proxy设置，其次尝试退出翻墙代理再试试。
