### ISSUE TITLE
通过钉钉发送通知之后，钉钉里边的信息点不开

### ISSUE THREAD

**Issue by silence9527** [trustyboy/xxqg-helper#22]
消息已经成功推送，但是不管是手机还是电脑都无法点开

![微信截图_20230108220028](https://user-images.githubusercontent.com/79163325/211200288-766a92dc-799c-42cd-89f4-abcf61631852.png)

**Comment by trustyboy** [comment]
需要手机版才能打开，手机需要同时安装学习强国app，并且钉钉的启动第三方app的权限需要开启

**Comment by silence9527** [comment]
已解决，把学习强国APP给隐藏了，放出来就好了
