### ISSUE TITLE
每日答题有问题，过不去啊

### ISSUE THREAD

**Issue by zhouyuyu888** [trustyboy/xxqg-helper#24]
每天都这样，做到第四题就进入死循环
=====================
2023-01-27 10:54:08
【多选题】
【题干】
<div>我国是世界上少数几个同时拥有（）、（）和（）三大生态系统的国家之一，广阔的滨海湿地为发展我国海洋碳汇提供了空间。</div>
【提示信息】
不知道
无
【多选题选项】
[]
包含提示的选项
不包含提示的选项 []

=====================
2023-01-27 10:54:10
【多选题】
【题干】
<div>我国是世界上少数几个同时拥有（）、（）和（）三大生态系统的国家之一，广阔的滨海湿地为发展我国海洋碳汇提供了空间。</div>
【提示信息】
不知道
无
【多选题选项】
[]
包含提示的选项
不包含提示的选项 []

=====================
2023-01-27 10:54:13
【多选题】
【题干】
<div>我国是世界上少数几个同时拥有（）、（）和（）三大生态系统的国家之一，广阔的滨海湿地为发展我国海洋碳汇提供了空间。</div>
【提示信息】
不知道
无
【多选题选项】
[]
包含提示的选项
不包含提示的选项 []

=====================
....重复
=====================
2023-01-28 09:56:23
【多选题】
【题干】
<div>下面选项中，属于海龟种类的有（）、（）、（）、（）。</div>
【提示信息】
['肯氏龟', '丽龟', '绿海', '龟', '平背龟']
海龟是海龟科、海龟属动物。生活于亚热带近海上层，终身生活于海洋中。世界上的海龟种类有<font color="red">肯氏龟</font>、<font color="red">丽龟</font>、玳瑁、<font color="red">绿海</font><font color="red">龟</font>、<font color="red">平背龟</font>等。
【多选题选项】
['A. 肯氏龟', 'B. 丽龟', 'C. 绿海龟', 'D. 平背龟']
包含提示的选项 ABCD
不包含提示的选项 []

=====================
2023-01-28 09:57:33
【多选题】
【题干】
<div>下面选项中，属于海龟种类的有（）、（）、（）、（）。</div>
【提示信息】
不知道
无
【多选题选项】
[]
包含提示的选项
不包含提示的选项 []

=====================
...重复
上面内容一直写日志。程序也不退出。每天都到第四题就出错。

**Comment by trustyboy** [comment]
是win版本还是docker版本？应该是答案识别有问题，如果会操作的话，你用源码版本把handless关闭掉，运行起来看看出错时候那一题是什么情况？
