### ISSUE TITLE
docker版做完题不自动关闭，会不停给钉钉推送消息，请问是我哪里设置错了吗，谢谢了

### ISSUE THREAD

**Issue by rizhaogw** [trustyboy/xxqg-helper#25]
![微信图片_20230201164750](https://user-images.githubusercontent.com/53533483/215994915-f4cd986e-1363-4888-9d74-60c8ac341bf0.jpg)
请问是我哪里设置错了吗，谢谢了

**Comment by trustyboy** [comment]
检查下你的docker是不是不断重启了

**Comment by h-2019** [comment]
能开一个开通PP的群组推送模式

**Comment by trustyboy** [comment]
> 能开一个开通PP的群组推送模式

目前已经支持PP一对一的消息，一对多的改下应该也没啥问题。主要内嵌在PP的链接很蛋疼，没法直接点，相对于钉钉用起来很不方便。感觉有点鸡肋。

**Comment by h-2019** [comment]
1，我用n1的armbian系统，开docker，钉钉推送的直接点链接，就自动跳转到确认登陆界面了，做完题，也会自动关闭，不存在一直给钉钉推送的情况。有可能是网络环境问题导致这样的情况。不过我遇到过，做题中途出错了，就一直循环这个错误步骤，不会自动跳出来，这个容器就宕机了，要人工重启docker才行。恐怕要加一个进程监控，一旦出现这种状况，就直接重启这个容器。
2，PP推送这个，其实也不麻烦，用浏览器打开推送的信息，再从浏览器点链接进入授权登陆界面即可。相比较钉钉，的操作，是多了一个步骤，不过可以少安装一个APP，也不错的。毕竟钉钉没有微信的用户群体大。
3，PP推送这个，在某些安卓手机可以直接从微信里面跳转到授权登陆界面，并不是所有的手机都不行。你可以在群里发一个调研看看，统计一下就知道了。不过苹果手机不能跳转出来。
另外，谢谢你做这个，给我们带来了极大的方便，平时工作忙死了，还要强制性完成，心累的很。真心感谢。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月8日(周三) 凌晨0:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [trustyboy/xxqg-helper] docker版做完题不自动关闭，会不停给钉钉推送消息，请问是我哪里设置错了吗，谢谢了 (Issue #25)




  
能开一个开通PP的群组推送模式
  
目前已经支持PP一对一的消息，一对多的改下应该也没啥问题。主要内嵌在PP的链接很蛋疼，没法直接点，相对于钉钉用起来很不方便。感觉有点鸡肋。

**Comment by trustyboy** [comment]
1、做题出错这个问题有些人出现，奇怪的是我自己用的时候都没出现。这个估计需要相关日志和题目才知道出错原因。有时间这块我理一下。
2、PP群组模式这个我抽空加下。

**Comment by trustyboy** [comment]
我今天貌似也出现了死循环，晚上回去调试下看看

**Comment by h-2019** [comment]
查看容器日志就看到了，这个问题会导致日志文件快速膨胀，对N1类的电视盒这种小主机不友好。毕竟只有3g左右的闲置空间。
可以对容器日志大小做限制，目前我限制在100M这样。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月8日(周三) 中午11:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [trustyboy/xxqg-helper] docker版做完题不自动关闭，会不停给钉钉推送消息，请问是我哪里设置错了吗，谢谢了 (Issue #25)




 
我今天貌似也出现了死循环，晚上回去调试下看看
