### ISSUE TITLE
docker版本滑块过去但是还是失败执行！能否在程序执行错误、失败后反馈给我重新执行

### ISSUE THREAD

**Issue by LVCC1596** [trustyboy/xxqg-helper#26]
[0m等待 [0m [0m4[0m [0m 秒[0m
[0m正在加载下一题[0m
[0mDEBUG-1016: 检测到滑块验证，正在尝试解锁 1次[0m
[0mDEBUG-1017: 解锁滑块失败正在刷新重试  2次[0m
[0mDEBUG-1016: 检测到滑块验证，正在尝试解锁 2次[0m
[0mDEBUG-1017: 解锁滑块失败正在刷新重试  3次[0m
[0mDEBUG-1016: 检测到滑块验证，正在尝试解锁 3次[0m
[0mDEBUG-1017: 解锁滑块失败正在刷新重试  4次[0m
[0mDEBUG-1016: 检测到滑块验证，正在尝试解锁 4次[0m
[0m已完成滑块解锁[0m
[0m检测到答案未成功提交，重新提交中[0m
[0m提交答案操作失败: Message: element click intercepted: Element ... is not clickable at point (1192, 650). Other element would receive the click: 
...

  (Session info: headless chrome=108.0.5359.125)
[0m
[0m检测到答案未成功提交，重新提交中[0m
[0m提交答案操作失败: Message: element click intercepted: Element ... is not clickable at point (1192, 650). Other element would receive the click: 
...

  (Session info: headless chrome=108.0.5359.125)
[0m
[0m检测到答案未成功提交，重新提交中[0m
[0m提交答案操作失败: Message: element click intercepted: Element ... is not clickable at point (1192, 650). Other element would receive the click: 
...

  (Session info: headless chrome=108.0.5359.125)
[0m
[0m★单选题[0m
[0m党的二十大通过的新修改的《中国共产党章程》指出，企业、农村、机关、学校、医院、科研院所、街道社区、社会组织、人民解放军连队和其他基层单位，凡是有正式党员（）以上的，都应当成立党的基层组织。[0m
[0m无法识别答案提示！[0m
[0m获取答题选项：[0m [0m[][0m
[0m包含提示的选项 [0m [0m[0m [0m，不包含提示的选项 [0m [0m[0m
[0m[91m无法根据提示判断，自动选择 A选项[39m[0m
[0m选择答案[0m [0mA[0m [0m失败！[0m
[0mMessage: element click intercepted: Element 
...
 is not clickable at point (952, 420). Other element would receive the click: 
...

  (Session info: headless chrome=108.0.5359.125)
[0m
[0m等待 [0m [0m5[0m [0m 秒[0m
Traceback (most recent call last):
[0m  File "XueQG.py", line 110, in 
[0m  File "answers/respond.py", line 215, in respond
[0m  File "func/Xuecore.py", line 381, in radio_check
[0m  File "func/Xuecore.py", line 441, in check_next_botton
[0m  File "selenium/webdriver/remote/webelement.py", line 80, in click
[0m  File "selenium/webdriver/remote/webelement.py", line 633, in _execute
[0m  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
[0m  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
[0mselenium.common.exceptions[0m.[0mElementClickInterceptedException[0m: [0mMessage: element click intercepted: Element ... is not clickable at point (1192, 650). Other element would receive the click: 
...

  (Session info: headless chrome=108.0.5359.125)
[0m
[0m[7] Failed to execute script 'XueQG' due to unhandled exception!

**Comment by trustyboy** [comment]
应该是滑块解锁出问题了，我看看

**Comment by trustyboy** [comment]
v0.7版本支持错误后发送消息给你，滑块问题暂时还未解决，重试几次好像就可以过去。等有空时候我仔细研究下。
