### ISSUE TITLE
windows版本做到35分就不做了

### ISSUE THREAD

**Issue by fatglobe** [trustyboy/xxqg-helper#27]
当前学习总积分：16901   今日得分：35
阅读文章: 12 / 12 , 视听学习: 6 / 6 , 文章时长: 12 / 12 , 视听时长: 6 / 6 ,
每日登陆: 1 / 1 , 每日答题: 5 / 5 , 每周答题: 0 / 0 , 专项答题: 5 / 1
============================================================
本程序 现支持以下模式（如未达到当日满分状态可重新运行）
------------------------------------------------------------
① 文章 + 视频
② 文章 + 视频 + 每日答题（★默认）
③ 文章 + 视频 + 每日答题 + 每周答题 + 专项答题
④ 每日答题 + 每周答题 + 专项答题
------------------------------------------------------------
读取到配置文件...选择模式: 3
------------------------------------------------------------
是否同时做文章和视频任务？（多线程）
同时做文章和视频任务可以节省时间，
但可能会增加封号风险，虽然现在此风险可以忽略不计
① 否 （★默认）
② 是
------------------------------------------------------------
读取到配置文件...选择模式: 2
============================================================
[*] Thread @正在运行: 文章学习
[*] 今天的文章学习已经完成，已退出
[*] Thread @正在运行: 视频学习
[*] 今天的视频学习已经完成，已退出
[*] 开始每日答题……
[*] 开始每周答题……

**Comment by trustyboy** [comment]
现在网页版一般就是35分。每周答题已经下架了
