### ISSUE TITLE
docker登录不上

### ISSUE THREAD

**Issue by LVCC1596** [trustyboy/xxqg-helper#28]
Traceback (most recent call last):
[0m  File "XueQG.py", line 43, in 
[0m  File "func/score.py", line 55, in show_userScore
[0m  File "func/score.py", line 11, in get_userScore
[0mTypeError[0m: [0m'NoneType' object is not subscriptable[0m
[0m[6] Failed to execute script 'XueQG' due to unhandled exception!
[0m[0m============================================================

**Comment by caileimeng** [comment]
我有一个账户也是这个情况

**Comment by caileimeng** [comment]
<html>
<body>
<div class="x-grid3-row" role="row" id="ext-gen505388" style="margin: 0px; padding: 0px; cursor: default; border-width: 0px 0px 1px; border-style: solid; border-top-color: initial; border-right-color: initial; border-bottom-color: rgba(198, 212, 224, 0.4); border-left-color: initial; border-image: initial; width: 657px; background-color: rgb(255, 255, 255); color: rgb(65, 75, 85); font-size: 13px; font-family: Verdana, Arial, &quot;Microsoft YaHei&quot;, sans-serif; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">

Traceback (most recent call last): | stdout
-- | --


</div>
</body>
</html>

**Comment by caileimeng** [comment]
Traceback (most recent call last):
  File "XueQG.py", line 43, in <module>
File "func/score.py", line 55, in show_userScore
File "func/score.py", line 11, in get_userScore
TypeError: 'NoneType' object is not subscriptable
[7] Failed to execute script 'XueQG' due to unhandled exception!

**Comment by mztwwww** [comment]
请问如何解决的呢？
