### ISSUE TITLE
得分35分？相加45分？

### ISSUE THREAD

**Issue by cyear** [trustyboy/xxqg-helper#36]
学习总积分: 3669 今日得分: 35
阅读文章: 12/12, 视听学习:6/6
文章时长: 12/12, 视听时长:6/6
每日答题: 5/5, 每日登陆:1/1
每周答题: 0/0, 专项答题:5/1

**Comment by trustyboy** [comment]
现在网页版一般就是35分。每周答题已经下架了，专项答题没有全做过的可以35，都做过了，只能30分。
