### ISSUE TITLE
教程

### ISSUE THREAD

**Issue by wang1kun** [trustyboy/xxqg-helper#39]
小白看了半天没看懂，想问问大佬们有没有教程啊，谢谢 /笑哭

**Comment by trustyboy** [comment]
docker版本看不懂，直接用windows版本好了，运行后扫描就行

**Comment by wang1kun** [comment]
> docker版本看不懂，直接用windows版本好了，运行后扫描就行

没有找到可以运行的，哈哈哈。   是exe包吗？

**Comment by trustyboy** [comment]
> > docker版本看不懂，直接用windows版本好了，运行后扫描就行
> 
> 没有找到可以运行的，哈哈哈。 是exe包吗？

到这边下载，解压后，运行里面的exe https://github.com/trustyboy/xxqg-helper/releases

**Comment by wang1kun** [comment]
> 到这边下载，解压后，运行里面的exe https://github.com/trustyboy/xxqg-helper/releases

好的，谢谢，嘿嘿
