### ISSUE TITLE
群晖里环境参数怎么写，才可以每天自动学习呢？

### ISSUE THREAD

**Issue by yyf051** [trustyboy/xxqg-helper#43]
群晖里环境参数怎么写，才可以每天自动学习呢？

**Comment by trustyboy** [comment]
没有用过群晖，定时学习，设置cron定时计划进行启动容器

**Comment by yanxi2018** [comment]
群晖怎么设置才能使用？需要先配置什么环境参数？我现在都不知道怎么先让他在群晖里运行起来

**Comment by trustyboy** [comment]
你去查询群晖docker怎么添加环境变量，然后看主页文档，把对应变量设置下就行。
