### ISSUE TITLE
xxqg-helper0.7-win版本闪退，之前用了一段时间没有问题。

### ISSUE THREAD

**Issue by amxoy** [trustyboy/xxqg-helper#49]
Traceback (most recent call last):
  File "XueQG.py", line 47, in <module>
  File "func\score.py", line 55, in show_userScore
  File "func\score.py", line 17, in get_userScore
TypeError: 'NoneType' object is not subscriptable
[13700] Failed to execute script XueQG

**Comment by trustyboy** [comment]
多试几次都是这个错误吗

**Comment by trustyboy** [comment]
用你们的账号登录xuexi.cn然后打开这个地址 https://pc-proxy-api.xuexi.cn/api/score/days/listScoreProgress?sence=score&deviceType=2 看看返回内容

**Comment by amxoy** [comment]
{"data":null,"message":"no right access","code":406,"error":null,"ok":false}

**Comment by Spykids-zerohc** [comment]
{"data":null,"message":"no right access","code":406,"error":null,"ok":false}

**Comment by trustyboy** [comment]
是扫码登录过xuexi.cn了吧，你们有没有其他账号试试。这个不是正常的返回结果。

**Comment by susan8991** [comment]
{"data":null,"message":"no right access","code":406,"error":null,"ok":false}
我也是返回这个结果，今天试了下用WIN的版本，也是报告这个错误

**Comment by trustyboy** [comment]
晚些发个版本修复下，api地址修改了导致的

**Comment by nbanywong** [comment]
感谢作者辛苦更新，挽救了我不少时间。

**Comment by trustyboy** [comment]
v0.8版本已经发布，解决了这个问题。

**Comment by amxoy** [comment]
感谢

**Comment by yhyandye** [comment]
谢谢作者！

**Comment by susan8991** [comment]
谢谢作者，又可以愉快的使用了
