### ISSUE TITLE
用你们的账号登录xuexi.cn然后打开这个地址 https://pc-proxy-api.xuexi.cn/api/score/days/listScoreProgress?sence=score&deviceType=2 看看返回内容

### ISSUE THREAD

**Issue by amxoy** [trustyboy/xxqg-helper#50]
用你们的账号登录xuexi.cn然后打开这个地址 https://pc-proxy-api.xuexi.cn/api/score/days/listScoreProgress?sence=score&deviceType=2 看看返回内容

_Originally posted by @trustyboy in https://github.com/trustyboy/xxqg-helper/issues/49#issuecomment-1478336766_
            {"data":null,"message":"no right access","code":406,"error":null,"ok":false}

**Comment by Spykids-zerohc** [comment]
{"data":null,"message":"no right access","code":406,"error":null,"ok":false}

**Comment by trustyboy** [comment]
#49
