### ISSUE TITLE
为什么一直闪退打不开呢

### ISSUE THREAD

**Issue by Angus9520** [trustyboy/xxqg-helper#58]
钉钉机器人推送现在关闭了接口，只能用pushplus，但是一直打不开XueQG.py

**Comment by trustyboy** [comment]
你把的配置、报错信息提供下。

**Comment by P1nk64** [comment]
> 你把的配置、报错信息提供下。

Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\xxx\AppData\Local\Temp\_MEI137842\pyzbar\libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by P1nk64** [comment]
> 你把的配置、报错信息提供下。

已解决，因为缺少动态链接库
下载[https://download.microsoft.com/download/F/3/5/F3500770-8A08-488E-94B6-17A1E1DD526F/vcredist_x64.exe](url)就可以用了

**Comment by P1nk64** [comment]
已解决，因为缺少动态链接库
下载[https://download.microsoft.com/download/F/3/5/F3500770-8A08-488E-94B6-17A1E1DD526F/vcredist_x64.exe](https://github.com/trustyboy/xxqg-helper/issues/url)
希望作者可以在readme里增加一条关于这个的提示

**Comment by P1nk64** [comment]
非常感谢，我是杨霄。您的消息我已收到，我会尽快回复。
