### ISSUE TITLE
有两个致命问题还请解决；答题过程发生错误：Message: element not interactable   (Session info: headless chrome=86.0.4240.111)

### ISSUE THREAD

**Issue by BarryYBL** [trustyboy/xxqg-helper#61]
问题
1、答题过程发生错误：Message: element not interactable (Session info: headless chrome=86.0.4240.111)
2、滑块验证出现错误；docker环境
<img width="975" alt="image" src="https://user-images.githubusercontent.com/46100874/228425994-16810993-67f3-441f-a7d3-e473d1641574.png">

**Comment by xhades1** [comment]
是不是滑块验证错误，导致答题失败

**Comment by xhades1** [comment]
> 滑块解锁问题，新版本在解决这个问题，目前还在测试中

是不是滑块验证错误，导致答题失败![Screenshot_20230329_181855_com.huawei.browser.jpg](https://user-images.githubusercontent.com/126909097/228505184-3b0a55d6-5de9-4434-9fd2-2ae2ae832fd9.jpg)
