### ISSUE TITLE
docker环境；获取用户cookie失败

### ISSUE THREAD

**Issue by BarryYBL** [trustyboy/xxqg-helper#62]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/46100874/228426290-7b034430-2d1a-45f8-b721-28fca5550b8a.png">

**Comment by BarryYBL** [comment]
但是应该是缓存失败了吧？因为我第一次脚本授权登录后执行完，再次执行还是没有cookie的

**Comment by klmmlk** [comment]
大佬，昨晚4点还在更新，注意圣体啊，不然到时候无国可强了。

**Comment by klmmlk** [comment]
大佬，建议定时学习还是在内部实现，然后可以做一个cookies保活，[https://github.com/sjkhsl/study_xxqg](url) 这个项目就是这种策略。

**Comment by trustyboy** [comment]
> 

这个项目是基于别人的改的，目前主要做修修补补的工作。这个版本暂时不会考虑添加一些额外功能，在考虑重写一个版本，到时会处理这些问题。
