### ISSUE TITLE
【BUG】关于自动退出

### ISSUE THREAD

**Issue by DoubleTree-Doge** [trustyboy/xxqg-helper#66]
修改配置文件Config/Config.cfg中
https://github.com/trustyboy/xxqg-helper/blob/5b4fec398860fefeee5defaea3bc0862013f8c2d/Config/Config.cfg#L44
为`AutoQuit = 1 `以开启自动退出功能后，直接在Python环境下运行[XueQG.py](https://github.com/trustyboy/xxqg-helper/blob/5b4fec398860fefeee5defaea3bc0862013f8c2d/XueQG.py)，由于func/common.py模块的以下代码存在，
https://github.com/trustyboy/xxqg-helper/blob/5b4fec398860fefeee5defaea3bc0862013f8c2d/func/common.py#L54
[XueQG.py](https://github.com/trustyboy/xxqg-helper/blob/5b4fec398860fefeee5defaea3bc0862013f8c2d/XueQG.py)中`xue_cfg: ConfigParser`的`xue_cfg["base"]["AutoQuit"]`总会被设置为0，这就导致
https://github.com/trustyboy/xxqg-helper/blob/5b4fec398860fefeee5defaea3bc0862013f8c2d/XueQG.py#L161-L162
中的判断条件`xue_cfg["base"]["AutoQuit"] == "0" and platform.system().lower() == 'windows'`总为`True`，`os.system("pause")`总是被执行，程序没有自动退出。

删除func/common.py模块的以下代码
https://github.com/trustyboy/xxqg-helper/blob/5b4fec398860fefeee5defaea3bc0862013f8c2d/func/common.py#L54
并将
https://github.com/trustyboy/xxqg-helper/blob/5b4fec398860fefeee5defaea3bc0862013f8c2d/XueQG.py#L161-L162
中的判断条件修改为
`xue_cfg["base"]["AutoQuit"] == "0" and platform.system().lower() == 'windows'`
（或者配置文件Config/Config.cfg中默认有`section: AutoQuit`）
可能可以解决该问题。

**Comment by trustyboy** [comment]
收到

**Comment by trustyboy** [comment]
#70
