### ISSUE TITLE
关于docker推送二维码失败

### ISSUE THREAD

**Issue by SolePeterP** [trustyboy/xxqg-helper#67]
在设置完dockerfile中的token后，启用docker显示二维码“已通过钉钉机器人发送成功”（或二维码“已通过pushplus发送成功”），但实际上在钉钉内（或在微信pushplus公众号上）未能收到相关消息推送，求助大佬解答！

注：在pushplus中已测试，可以在官网中发送消息在微信pushplus公众号中接收推送，但在docker中运行无法接收二维码消息

**Comment by trustyboy** [comment]
dockerfile中设置token？

**Comment by SolePeterP** [comment]
不好意思说错了。。是在Config/Config.cfg文件中设置token后仍无法成功接收二维码。。而且发现在删除token内容并重装容器后，使用pushplus推送二维码仍显示”“已通过pushplus发送成功“

**Comment by trustyboy** [comment]
docker创建容器时候是否设置了token环境变量，如果设置了，会优先使用环境变量里面的token。另外，目前推送结果没有对返回结果进行判断，所以token错误可能会有误判，后续加下发送结果判断。

**Comment by SolePeterP** [comment]
感谢！！目前解决办法是在程序目录cmd中，输入的docker run命令，将 `PPtoken=PlusPushtoken` 改为 `PPtoken=[自己的token]`，成功接收推送
