### ISSUE TITLE
这两天官方估计又改了什么了，需要再研究下

### ISSUE THREAD

**Issue by xxhades** [trustyboy/xxqg-helper#69]
这两天官方估计又改了什么了，需要再研究下

_Originally posted by @trustyboy in https://github.com/trustyboy/xxqg-helper/issues/68#issuecomment-1499305467_
         是的，这几天一直学习不得分，需要重启几次才行

**Comment by trustyboy** [comment]
#70 已修复

**Comment by xhades1** [comment]
![IMG_20230409_143446.jpg](https://user-images.githubusercontent.com/126909097/230758345-32cae197-ddbe-4392-bf02-ab4585e5e021.jpg)大佬，最近PP不会推送了

**Comment by xxhades** [comment]
换了个新的pp又可以了。。。
