### ISSUE TITLE
二维码截图扫码登录失败

### ISSUE THREAD

**Issue by LVCC1596** [trustyboy/xxqg-helper#75]
[0m发送失败. 错误信息: PlusPush发送失败：请求成功[0m
[0m登录过程发生错误：PlusPush发送失败：请求成功[0m
[0m发送失败. 错误信息: PlusPush发送失败：请求成功[0m
Traceback (most recent call last):
[0m  File "XueQG.py", line 42, in 
[0m  File "func/Xuecore.py", line 175, in logging
[0m  File "func/Xuecore.py", line 209, in sendMessage
[0m  File "func/pluspush.py", line 47, in ppmsgsend
[0m  File "func/pluspush.py", line 43, in ppmsgsend
[0mException[0m: [0mPlusPush发送失败：请求成功[0m
[0m
During handling of the above exception, another exception occurred:

[0mTraceback (most recent call last):
[0m  File "XueQG.py", line 46, in 
[0m  File "func/common.py", line 120, in sendMessage
[0m  File "func/pluspush.py", line 47, in ppmsgsend
[0m  File "func/pluspush.py", line 43, in ppmsgsend
[0mException[0m: [0mPlusPush发送失败：请求成功[0m
[0m[6] Failed to execute script 'XueQG' due to unhandled exception!
[0m[0m

**Comment by trustyboy** [comment]
#76 

已经修复，更新下。重建docker容器。
