### ISSUE TITLE
0.13版本修复检测问题了吗

### ISSUE THREAD

**Issue by Kevinyang-ops** [trustyboy/xxqg-helper#78]
0.1版本用了2次被官方检测到了

**Comment by trustyboy** [comment]
官方检测到？这个我自己也用了很久了，没发现被检测到。也没看有人反馈。

**Comment by dongoufei** [comment]
最近用好像都被官方检测到了。。

**Comment by trustyboy** [comment]
截个图我瞧瞧

**Comment by Kevinyang-ops** [comment]
> 截个图我瞧瞧

![Screenshot_20230415_084030](https://user-images.githubusercontent.com/77831410/232174649-783e0b9a-d31d-4ad5-bec3-c4d45cb0b39e.jpg)
就这样子，主要是我最近也没怎么打开。会不会是因为之前有天我看程序闪退了又重复打开导致的

**Comment by trustyboy** [comment]
这个没法确定，检测手段有多种方式。暂时不知道怎么被检测。之前今日答题出现滑块，chromedriver被检测到，导致解锁失败。后面版本已经去掉特征符。

**Comment by ggjj862** [comment]
我也被检测到了。不敢用了

**Comment by yhy729** [comment]
也被检测到了
”经系统检测，您的账号存在不规范学习行为，若再次发现，将被执行相应处理，请规范学习行为。“

**Comment by trustyboy** [comment]
怕封号的请慎用。 最新版本已经发布，请看这个 #81
