### ISSUE TITLE
定时开始学习问题请教

### ISSUE THREAD

**Issue by sntyuxi** [trustyboy/xxqg-helper#8]
请教一下，这个该在哪里配置定时学习？
![image](https://user-images.githubusercontent.com/96931261/208007196-0f6e652d-6faa-46a9-919f-54bb800b3b06.png)

可以使用cron来定时启动docker进行学习，例如每天上午9:30开始学习

30 9 * * * docker start xxqg

**Comment by sntyuxi** [comment]
原来我这是在群晖中，设置不同，可以直接在任务中定时执行任务。谢谢老大的软件，黑群晖通过plus正常运行

**Comment by trustyboy** [comment]
> 原来我这是在群晖中，设置不同，可以直接在任务中定时执行任务。谢谢老大的软件，黑群晖通过plus正常运行

群晖我也没用过，不知道怎么设置，不过应该也可以设定定时执行某些命令，你设置下定时执行命令`docker start xxqg` 应该是可以的
