### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by LVCC1596** [trustyboy/xxqg-helper#85]
Traceback (most recent call last):
[0m  File "XueQG.py", line 74, in 
[0m  File "func/score.py", line 58, in show_userScore
[0m  File "func/score.py", line 14, in get_userScore
[0mTypeError[0m: [0m'NoneType' object is not subscriptable[0m
[0m[6] Failed to execute script 'XueQG' due to unhandled exception!
[0m[0m

**Comment by LVCC1596** [comment]
能否修改一下
        except:
            print("=" * 60)
            print("内置驱动初始化失败")
            print("=" * 60)
            raise为        except (Exception, BaseException) as e:
            print(e)
            print(repr(e))
            exstr = traceback.format_exc()
            print(exstr)
            print("=" * 60)
            print("内置驱动初始化失败")
            print("=" * 60)
            raise

**Comment by LVCC1596** [comment]
![image](https://user-images.githubusercontent.com/33076061/233513172-475a7227-a183-4e68-b259-2b3ee32c2142.png)
使用源码运行提示程序包损坏

**Comment by xiaoWangSec** [comment]
请尝试删除`User`目录后重新登录

**Comment by LVCC1596** [comment]
> 请尝试删除`User`目录后重新登录

重建后恢复
